// ==UserScript==
// @name iPT filter
// @namespace http://github.com/nightbread
// @version 0.0.10
// @encoding utf-8
// @license https://opensource.org/licenses/MIT
// @homepage https://github.com/nightbread/userscripts
// @description Do not use.
// @author nightbread
// @include https://iptorrents.eu/t*
// @updateURL https://raw.githubusercontent.com/nightbread/userscripts/master/ipt-filter.user.js
// @downloadURL https://raw.githubusercontent.com/nightbread/userscripts/master/ipt-filter.user.js
// @supportURL https://github.com/nightbread/userscripts/issues
// ==/UserScript==

(function() {
    'use strict';

    const xvidIPTTeam = /XviD-iPT Team/;
    const prefixes = new RegExp('^(' + [
        'Wild Party Girls',
        'JamesDeen',
        'SexArt',
        'BangBus',
        '(Exotic|Tiny|Beauty)4K',
        'TheTrainingofO',
        'EvilAngel',
        'StraplessDildo',
        'MilfThing',
        'Only(?:Teen)?BlowJobs?',
        'PetiteHDPorn',
        'DirtyWivesClubs',
        'MonstersOfCock',
        'MoneyTalks',
        'FTV',
        'ElectroSluts',
        'DeviceBondage',
        'NetVideoGirls',
        'WildOnCam',
        'Czech[CMS]',
        'Only-(?:Opaque|Secretarie)s',
        'ATK[A-Z]',
        'Passion-HD',
        'FullyClothed',
        'Karups[A-Z]',
        'DigitalPlayground',
        'AuntJudys',
        'MontysPOV',
        'Naked News',
        'WowGirls',
        'AllFineGirls',
        'Euro(?:SexParties|TeenErotica|GirlsOnGirls)',
        'DontBreakMe',
        '1ByDay',
        'FemJoy',
        'Playboy[A-Z]',
        'All(?:Over30|Internal)',
        '(?:BoxTruck|Sneaky)Sex',
        'BangBrosClips',
        'SinsLife',
        'DeepThroatSirens',
        'Big(?:GulpGirls|Naturals)',
        'JulesJordan',
        'MySistersHotFriend',
        'MetArtX?',
        'MeloneChallenge',
        'Hegre',
        'Nubile(?:s|Films)',
        'Anilos',
        'CumFiesta',
        '(?:VI|WetAnd)P(issy|uffy)',
        'ImmoralLive',
        'DoctorAdventures',
        'Pornstar(Platinum|sLikeItBig)',
        'TeensLikeItBig',
        'InnocentHigh',
        'X-Angels',
        'ReadyOrNot',
        'MomXXX',
        'Colette',
        'Throated',
        'HardX',
        'BlackIsBetter',
        'TheLifeErotic',
        'Spizoo',
        'SweetSinner',
        'PixAndVideo',
        'HotLegsAndFeet',
        'DDFBusty',
        '(?:GloryHole|Lady)Voyeurs',
        'KinkyFamily',
        'Porn(?:Fidelity|MegaLoad)',
        '(?:Lub|Hol)ed',
        'LANewGirl',
        'PunishTeens',
        'TeenPies',
        'Public(?:Disgrace|PickUps|Agent)',
        'Vixen',
        'Anal-Beauty',
        '(?:Female)?Fake(?:Cop|Agent|Taxi|Hospital)',
        'TheFuckingRoom',
        'FamilyStrokes',
        'ExxxtraSmall',
        'Dirty-Doctor',
        'MyFriendsHot(?:Girl|Mom)',
        'SisLovesMe',
        'HollyRandall',
        'Black(?:ed|GFs)',
        '(?:Fitness|Massage)Rooms',
        'LivingWithAPornstar',
        '(?:Backroom)?CastingCouch',
        'AssParade',
        'WhippedAss',
        'InTheCrack',
        'JesseLoads',
        'LosConsoladores',
        'WeLikeToSuck',
        'MyFirstSexTeacher',
        'ALSScan',
        'PlumperPass',
        'Paintoy',
        'DigitalDesire',
        'GFRevenge',
        'BrokeModel',
        'SinfulXXX',
        'HerLimit',
        'UpHerAsshole',
        'MILF(?:Hunter|sLikeItBig)',
        'TakeVan',
        'NewSensations',
        'Bang\\s?Casting',
        'VintageFlash',
        'StreetBlowJobs',
        'ShareMyBF',
        'BigTits(?:AtWork|OnScreen|AtSchool)',
        'BigTitsRoundAsses',
        'DPFanatics',
        'FootsieBabes',
        '21(?:EroticAnal|Naturals)',
        'Cosmid',
        'SapphicErotica',
        'AbbyWinters',
        'X-Art',
        'Only(?:Tease|SilkAndSatin)',
        'PrivateSociety',
        'DadCrush',
        'TwistysHard',
        'ALSAngels',
        'FemaleAgent',
        'JoshStoneXXX',
        '(POVD?|Girlfriends|Defloration|Babes)\\s(?:[0-9]{2}\\s){3}',
        '(?:Mean|Fantasy|Nuru|MyNaughty)Massage',
        '(?:WoodmanCasting|Brutal)X',
        'XXX(?: Pawn|Shades)',
        'MomKnowsBest',
        'AlexLegend',
        'ColombiaFuckFest',
        'I(?:HaveAWife|KnowThatGirl)',
        'FuckedInTraffic',
        'Relaxxxed',
        'MonsterCurves',
        'VelvetEcstacy',
        'HandsOnHardcore',
        'DirtyMasseur',
        'TeachMeFisting',
        'BurningAngel',
        'ButtPlays',
        'AssholeFever',
        'LetsTryAnal',
        'Killergram',
        'Sex(?:AndSubmission|uallyBroken)',
        'Tushy',
        'VivThomas',
        'PervyOnes',
        'TMWVRNet',
        'TheRealWorkout',
        'DaughterSwap',
        'Ex-Girlfriends',
        'ThisGirlSucks',
        'DaneJones',
        'BlacksOn',
        'FutileStruggles',
        'TeensLoveAnal',
        'StreetSuckers',
        'SinsLife',
        'MikesApartment',
        'Bang\\s?RealTeens',
        'HouseOfTaboo',
        'Pantyhosed4U',
        'Real(WifeStories|ExGirlfriends)',
        'GrandpasFuckTeens',
        'MommyBlowsBest',
        'StepMomLessons',
        'POVBitch',
        'BashBastards',
        'MormonGirlz',
        '(?:The)?UpperFloor',
        'LANewGirl',
        'OldYoung',
        'Fucking(Glasses|Machines)',
        'FirstAnalDate',
        'ExploitedCollegeGirls',
        'UltimateSurrender',
        'KellyMadison',
        'Shoplyfter',
        'WankzVR',
        'ChocolateBJs',
        'PascalsSub',
        'CumPerfection',
        '1By-Day',
        'RoccoSiffredi',
        'NaughtyOffice',
        'Joymii',
        'TeensLoveHugeCocks',
        'HardTied',
        'SpyTug',
        '(?:Amateur|Pure)CFNM',
        'HuCows',
        'CumClinic,
        'TeenDreams',
        'VirtualXPorn',
        'TonightsGirlfriend',
        'BrownBunnies',
        'VelvetEcstacy',
        'BitchesAbroad',
        'AGirlKnows',
        'PropertySex',
        'FootFetish',
        'StepSiblingsCaught',
        'GloryHole(Swallow|Secrets)',
        'GangbangCreampie',
        'CrazyAsianGFs',
        'RoundAndBrown',
        '8thStreetLatinas',
        'LarasPlayground',
        'SheWillCheat',
        'JimSlip',
        'Zoliboy',
        'PrettyDirty',
        '(?:Erotica|Dark)X',
        '21FootArt',
        'PervsOnPatrol',
        'HogTied',
        'BrutalCastings'
    ].join('|') + ')', 'i');
    const removeRegexes = [
        /(?:SPANISH|ITALIAN|FRENCH|DUTCH) XXX/i,
        /WifeSwap/i,
        prefixes,
    ];
    const lesbo = /\blesb(?:ian|o)\b/i;
    const SELECTOR = '#torrents > tbody > tr > td > a';

    Array.from(document.querySelectorAll(SELECTOR)).forEach(function(el, i) {
        const row = el.parentElement.parentElement;

        if (xvidIPTTeam.test(el.innerText)) {
            row.remove();
            return;
        }

        removeRegexes.forEach(function (regex) {
            if (regex.test(el.innerText) && !lesbo.test(el.innerText)) {
                row.remove();
            }
        });
    });
})();
