// ==UserScript==
// @name iPT filter
// @namespace http://github.com/nightbread
// @version 0.0.24
// @encoding utf-8
// @license https://opensource.org/licenses/MIT
// @homepage https://github.com/nightbread/userscripts
// @description Do not use.
// @author nightbread
// @include https://iptorrents.eu/t*
// @updateURL https://raw.githubusercontent.com/nightbread/userscripts/master/ipt-filter.user.js
// @downloadURL https://raw.githubusercontent.com/nightbread/userscripts/master/ipt-filter.user.js
// @supportURL https://github.com/nightbread/userscripts/issues
// ==/UserScript==

(function() {
    'use strict';

    const xvidIPTTeam = /XviD-iPT Team/;
    const prefixes = new RegExp('^(' + [
        'Czech',
        'PureMature',
        'WankItNow',
        'WakeUp'
        'Gyno-X',
        'ZebraGirls',
        'MyBabysittersClub',
        'InterracialPickups',
        'Real(?:GFS|Black)Exposed',
        'VelvetEcstacy',
        'FeatureFilms',
        'CougarSeason',
        'BrutalDildos',
        'BrickYates',
        'GirlsDo[A-Z]',
        'MissLingLing',
        'TokyoHot',
        'HelplessTeens',
        'Piss',
        'Ebony',
        'AbbyWinters',
        'ShesBrandNew',
        'Wild Party Girls',
        'JamesDeen',
        'SexArt',
        'BangBus',
        'Watch4Beauty',
        '(Exotic|Tiny|Beauty)4K',
        'TheTrainingofO',
        'EvilAngel',
        'StraplessDildo',
        'MilfThing',
        'Only(?:Teen)?BlowJobs?',
        'PetiteHDPorn',
        'DirtyWivesClub',
        'MonstersOfCock',
        'MoneyTalks',
        'FTV',
        'ElectroSluts',
        'DeviceBondage',
        'NetVideoGirls',
        'WildOnCam',
        'Czech[CMS]',
        'Only-(?:Opaque|Secretarie)s',
        'ATK[A-Z]',
        'Passion-HD',
        'FullyClothed',
        'Karups[A-Z]',
        'DigitalPlayground',
        'AuntJudys',
        '(?:Tease|Montys)POV',
        'BitchConfessions',
        'BangBros18',
        'Naked News',
        'WowGirls',
        'AllFineGirls',
        'Euro(?:SexParties|TeenErotica|GirlsOnGirls)',
        'DontBreakMe',
        '1ByDay',
        'FemJoy',
        'Playboy[A-Z]',
        'All(?:Over30|Internal)',
        '(?:BoxTruck|Sneaky)Sex',
        'BangBrosClips',
        'SinsLife',
        'DeepThroatSirens',
        'Big(?:GulpGirls|Naturals|WetButts|Butts)',
        'JulesJordan',
        'My(?:SistersHot|GirlfriendsBusty)Friend',
        'MetArtX?',
        'MeloneChallenge',
        'Hegre',
        'Nubile(?:s|Films)',
        'Anilos',
        'CumFiesta',
        '(?:VI|WetAnd)P(issy|uffy)',
        'ImmoralLive',
        'DoctorAdventures',
        'Pornstar(Platinum|sLikeItBig)',
        'TeensL(?:ikeItBig|oveBlackCock)',
        'InnocentHigh',
        'X-Angels',
        'ReadyOrNot',
        'Mom(?:XXX|sInControl|myGotBoobs)',
        'Slimewave',
        'AllWam',
        'Leather',
        'Ginger',
        'Bra[zs]il',
        'Colette',
        'Throated',
        'HardX',
        'BlackIsBetter',
        'TheLifeErotic',
        'Spizoo',
        'SweetSinner',
        'PixAndVideo',
        'HotLegsAndFeet',
        'DDFBusty',
        '(?:GloryHole|Lady)Voyeurs',
        'KinkyFamily',
        'Porn(?:Fidelity|MegaLoad)',
        '(?:Lub|Hol)ed',
        'LANewGirl',
        '(?:Stranded|Punish)Teens',
        'TeenPies',
        'Public(?:Disgrace|PickUps|Agent)',
        'Vixen',
        'AnalOverdose',
        '(?:First)?Anal(?:-Beauty|TeenAngels|Quest)',
        '(?:Female)?Fake(?:Cop|Agent|Taxi|Hospital)',
        'TheFuckingRoom',
        'FamilyStrokes',
        'ExxxtraSmall',
        'Dirty-Doctor',
        'MyFriendsHot(?:Girl|Mom)',
        'SisLovesMe',
        'HollyRandall',
        'Black(?:ed|GFs)',
        '(?:Fitness|Massage)Rooms',
        'LivingWithAPornstar',
        '(?:Backroom)?CastingCouch',
        'AssParade',
        'WhippedAss',
        'InTheCrack',
        'JesseLoads',
        'LosConsoladores',
        'WeLikeToSuck',
        'MyFirstSexTeacher',
        'ALSScan',
        'PlumperPass',
        'Paintoy',
        'DigitalDesire',
        'GFRevenge',
        'BrokeModel',
        'SinfulXXX',
        'HerLimit',
        'UpHerAsshole',
        'MILF(?:Hunter|sLikeItBig)',
        'TakeVan',
        'NewSensations',
        'Bang\\s?Casting',
        'VintageFlash',
        'StreetBlowJobs',
        'ShareMyBF',
        'BigTits(?:AtWork|OnScreen|AtSchool)',
        'BigTitsRoundAsses',
        'DPFanatics',
        'FootsieBabes',
        '21(?:EroticAnal|Naturals)',
        'Cosmid',
        'SapphicErotica',
        'AbbyWinters',
        'X-Art',
        'Only(?:Tease|SilkAndSatin)',
        'PrivateSociety',
        'DadCrush',
        'TwistysHard',
        'ALSAngels',
        'FemaleAgent',
        'JoshStoneXXX',
        '(POVD?|Swallowed|Girlfriends|Defloration|Babes)\\s(?:[0-9]{2}\\s){3}',
        'Tushy',
        '(?:Mean|Fantasy|Nuru|MyNaughty)Massage',
        '(?:WoodmanCasting|Brutal)X',
        'MassageCreep',
        'SimplyAnal',
        'FisterTwister',
        'HardcoreGangbang',
        'XXX(?: Pawn|Shades)',
        'MomKnowsBest',
        'AlexLegend',
        'ColombiaFuckFest',
        'I(?:HaveAWife|KnowThatGirl)',
        'FuckedInTraffic',
        'Relaxxxed',
        'MonsterCurves',
        'VelvetEcstacy',
        'HandsOnHardcore',
        'DirtyMasseur',
        'TeachMeFisting',
        'BurningAngel',
        'ButtPlays',
        'EverythingButt',
        'BackstageBeginners',
        'PortaGloryhole',
        'AsianaStarr',
        'VelvetEcstacy',
        'BlackPatrol',
        'AssholeFever',
        'LetsTryAnal',
        'Killergram',
        'Sex(?:AndSubmission|uallyBroken)',
        'Tushy',
        'VivThomas',
        'PervyOnes',
        'TMWVRNet',
        'TheRealWorkout',
        'DaughterSwap',
        'Ex-Girlfriends',
        'ThisGirlSucks',
        'DaneJones',
        'BlacksOn',
        'FutileStruggles',
        'Teen(?:sLoveAnal|Curves)',
        'StreetSuckers',
        'SinsLife',
        'MikesApartment',
        'Bang\\s?RealTeens',
        'HouseOfTaboo',
        'Pantyhosed4U',
        'Real(WifeStories|ExGirlfriends)',
        'GrandpasFuckTeens',
        'MommyBlowsBest',
        'StepMomLessons',
        'POVBitch',
        'BashBastards',
        'MormonGirlz',
        '(?:The)?UpperFloor',
        'LANewGirl',
        'OldYoung',
        'Fucking(Glasses|Machines)',
        'Teen(?:Aanalyzed|Fidelity)',
        'FirstAnalDate',
        '(?:ExploitedCollege|BlowBang)Girls',
        'UltimateSurrender',
        'KellyMadison',
        'Shoplyfter',
        'WankzVR',
        'ChocolateBJs',
        'PascalsSub',
        'CumPerfection',
        '1By-Day',
        'RoccoSiffredi',
        'NaughtyOffice',
        'Joymii',
        'TeensLoveHugeCocks',
        'HardTied',
        'SpyTug',
        '(?:Amateur|Pure)CFNM',
        'HuCows',
        'CumClinic',
        'TeenDreams',
        'VirtualXPorn',
        'TonightsGirlfriend',
        'BrownBunnies',
        'VelvetEcstacy',
        'BitchesAbroad',
        'AGirlKnows',
        'PropertySex',
        'FootFetish',
        'StepSiblingsCaught',
        'GloryHole(Swallow|Secrets)',
        'GangbangCreampie',
        'CrazyAsianGFs',
        'RoundAndBrown',
        '8thStreetLatinas',
        'LarasPlayground',
        'SheWillCheat',
        'JimSlip',
        'Zoliboy',
        'PrettyDirty',
        '(?:Erotica|Dark)X',
        '(?:21Foot|Rylsky)Art',
        'PervsOnPatrol',
        'HogTied',
        'BrutalCastings',
        'MatureNL',
        'Yonitale',
        'OrgasmWorldChampionship'
    ].join('|') + ')', 'i');
    const removeRegexes = [
        /(?:SPANISH|ITALIAN|FRENCH|DUTCH) XXX/i,
        /WifeSwap/i,
        /FTV\s/,
        prefixes,
    ];
    const lesbo = /\blesb(?:ian|o)\b/i;
    const SELECTOR = '#torrents > tbody > tr > td > a';

    Array.from(document.querySelectorAll(SELECTOR)).forEach(function(el, i) {
        const row = el.parentElement.parentElement;

        if (xvidIPTTeam.test(el.innerText)) {
            row.remove();
            return;
        }

        removeRegexes.forEach(function (regex) {
            if (regex.test(el.innerText) && !lesbo.test(el.innerText)) {
                row.remove();
            }
        });
    });
})();
